// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapidersi.Repositories;

#nullable disable

namespace webapidersi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230902134135_ekleme")]
    partial class ekleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapidersi.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            About = "İtalyan rönesans dönemi ressam, heykeltıraş, mimar ve şairidir.",
                            Name = "Michelangelo"
                        },
                        new
                        {
                            ArtistId = 2,
                            About = "Portekizli ressam ve desinatör",
                            Name = "Paula Rego"
                        });
                });

            modelBuilder.Entity("webapidersi.Models.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExhibitionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExhibitionId");

                    b.ToTable("Exhibitions");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            Description = "kskskjfjffsf",
                            Name = "Hikayelerin Hikayesi"
                        },
                        new
                        {
                            ExhibitionId = 2,
                            Description = "aaaaa",
                            Name = "Varoluş ve Yüzey"
                        });
                });

            modelBuilder.Entity("webapidersi.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ProfileId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "zincirberivan@gmail.com",
                            Name = "Bilge Berivan ",
                            Password = 147414,
                            ProfileId = 2,
                            Surname = "Zincir"
                        },
                        new
                        {
                            ID = 2,
                            Email = "derincagdas@gmail.com",
                            Name = "Derin",
                            Password = 150707,
                            ProfileId = 1,
                            Surname = "Çağdaş"
                        });
                });

            modelBuilder.Entity("webapidersi.Models.Museum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Museums");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Asmalı Mescit, Meşrutiyet Cd. No:65, 34430 Beyoğlu/İstanbul",
                            City = "İstanbul",
                            Country = "Türkiye",
                            Name = "Pera Müzesi"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Via del Proconsolo,4,50122",
                            City = "Florence",
                            Country = "Italy",
                            Name = "Bargello Müzesi"
                        });
                });

            modelBuilder.Entity("webapidersi.Models.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fallowers")
                        .HasColumnType("int");

                    b.Property<int>("Fallowing")
                        .HasColumnType("int");

                    b.Property<string>("Favorites")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visited")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ProfileId = 1,
                            Comment = "Büyüleyici bir eser",
                            Fallowers = 1,
                            Fallowing = 1,
                            Visited = "fsfsff"
                        },
                        new
                        {
                            ProfileId = 2,
                            Comment = "Büyüleyici bir yer",
                            Fallowers = 1,
                            Fallowing = 1,
                            Visited = "jsdjsks"
                        });
                });

            modelBuilder.Entity("webapidersi.Models.Work", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<string>("Kunye")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ExhibitionId");

                    b.ToTable("Works");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Aciklama = "Adem'in Yaratılışı, Sistine Şapeli'nin tavanındaki ünlü bir fresktir Tüm zamanların en çok replikası yapılan dinî resimlerinden biridir.",
                            ArtistId = 1,
                            ExhibitionId = 2,
                            Kunye = "Michelangelo,Adem'in Yaratılışı,1512,2,8 m x 5,7 m"
                        },
                        new
                        {
                            ID = 2,
                            Aciklama = "ay ışığının aydınlattığı bir kumsalda ön planda dans eden sekiz figürün yer aldığı büyük bir tablodur.",
                            ArtistId = 2,
                            ExhibitionId = 1,
                            Kunye = "Paula Rego, The Dance, 1988"
                        });
                });

            modelBuilder.Entity("webapidersi.Models.Member", b =>
                {
                    b.HasOne("webapidersi.Models.Profile", "Profile")
                        .WithMany("Members")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("webapidersi.Models.Work", b =>
                {
                    b.HasOne("webapidersi.Models.Artist", "Artist")
                        .WithMany("Works")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapidersi.Models.Exhibition", "Exhibition")
                        .WithMany("Works")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("webapidersi.Models.Artist", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("webapidersi.Models.Exhibition", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("webapidersi.Models.Profile", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
